{% set name = "slabdip" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/slabdip-{{ version }}.tar.gz
  sha256: 3707d6873526bb02fccc68bc3d54e87e80957bd716ab9ac65388c6547b6db9a7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pandas
    - numpy
    - gplately >=0.4
    - scikit-learn

test:
  imports:
    - slabdip
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/brmather/Slab-Dip
  summary: Python package to calculate slab dip using simple plate kinematic parameters
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brmather
